name: hacker_news_clone
description: A hobby project. hacker news clone in flutter.
publish_to: none
version: 1.0.0+4
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  hemend_async_log_recorder: ^0.1.13+1
  hemend_logger: ^0.2.6+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  rxdart: ^0.27.7
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
